name: Build abstract machine with nix
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-abstract-machine:
    runs-on: nix
    steps:
      - uses: https://github.com/cachix/cachix-action@v14
        with:
          name: ysyx
          authToken: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build abstract-machine
        run: |
          nix build .?submodules=1#abstract-machine
      - name: Build nemu
        run: |
          nix build .?submodules=1#nemu

